name: Build Custom Kali Linux for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl

      - name: Clone Kali ARM Build Scripts
        run: |
          git clone https://gitlab.com/kalilinux/build-scripts/kali-arm.git
          cd kali-arm
          chmod +x build.sh

      - name: Build Custom Kali Image
        run: |
          cd kali-arm
          sudo ./build.sh --board raspberry-pi --arch arm64 --variant minimal --verbose

      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kali-linux-raspberrypi
          path: kali-arm/images/*.img.xz
