name: Build Kali ARM Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl qemu-user-static debootstrap coreutils systemd-container

      - name: Clone Kali ARM build scripts
        run: |
          git clone https://gitlab.com/kalilinux/build-scripts/kali-arm.git
          cd kali-arm
          chmod +x *.sh

      - name: Run Raspberry Pi build script
        run: |
          cd kali-arm
          sudo bash -x ./raspberry-pi.sh 2>&1 | tee build.log
          exit ${PIPESTATUS[0]}

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: kali-arm/build.log
          if-no-files-found: warn

      - name: Upload Kali Linux Image
        uses: actions/upload-artifact@v4
        with:
          name: kali-linux-raspberrypi
          path: kali-arm/images/*.img.xz
          if-no-files-found: warn
