name: Build Custom Kali ARM Image for Raspberry Pi 4 (64-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install Git
        run: |
          sudo apt update
          sudo apt install -y git
          git --version

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Clean Submodules
        run: |
          git submodule deinit -f . || true
          git submodule update --init --recursive || true

      - name: Install Base Dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl wget qemu-user-static debootstrap coreutils systemd-container gnupg \
            build-essential bc kmod libncurses-dev libelf-dev libssl-dev bison flex crossbuild-essential-arm64 \
            parted xz-utils eatmydata mmdebstrap e2fsprogs

      - name: Install kali-archive-keyring
        run: |
          wget https://kali.download/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2024.1_all.deb
          sudo dpkg -i kali-archive-keyring_2024.1_all.deb
          rm kali-archive-keyring_2024.1_all.deb

      - name: Set Safe TERM Variable
        run: echo "TERM=xterm-256color" >> $GITHUB_ENV

      - name: Clone Kali ARM Build Scripts
        run: |
          git clone --recurse-submodules https://gitlab.com/kalilinux/build-scripts/kali-arm.git
          cd kali-arm
          chmod +x *.sh

      - name: Clone Raspberry Pi Kernel Source
        run: |
          # Retry clone up to 3 times with 10s delay on failure
          for i in {1..3}; do
            git clone --depth=1 --branch rpi-6.6.y --progress https://github.com/raspberrypi/linux.git 2>&1 | tee clone.log && break
            echo "Clone attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
          if [ ! -d "linux" ]; then
            echo "Error: Failed to clone kernel repo after 3 attempts"
            cat clone.log
            exit 1
          fi
          cd linux
          git checkout rpi-6.6.y

      - name: Configure Custom Kernel for Pentesting
        run: |
          cd linux
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig
          sed -i 's/# CONFIG_BT_HCIUART is not set/CONFIG_BT_HCIUART=y/' .config
          sed -i 's/# CONFIG_BT_HCIUART_H4 is not set/CONFIG_BT_HCIUART_H4=y/' .config
          sed -i 's/# CONFIG_BT_HCIUSB is not set/CONFIG_BT_HCIUSB=y/' .config
          echo "CONFIG_CFG80211=y" >> .config
          echo "CONFIG_MAC80211=y" >> .config
          echo "CONFIG_RFKILL=y" >> .config
          echo "CONFIG_USB_STORAGE=y" >> .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

      - name: Compile Custom Kernel
        run: |
          cd linux
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) Image modules dtbs
          mkdir -p ../kernel-build/overlays
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=../kernel-build modules_install
          cp arch/arm64/boot/Image ../kernel-build/kernel8.img
          cp arch/arm64/boot/dts/broadcom/*.dtb ../kernel-build/
          cp arch/arm64/boot/dts/overlays/*.dtbo ../kernel-build/overlays/
          cp -r . ../kernel-source

      - name: Build Kali Image with Custom Kernel
        run: |
          cd kali-arm
          sudo ARCH=arm64 bash -x ./raspberry-pi-64-bit.sh 2>&1 | tee build.log || { echo "Script failed, check build.log"; exit 1; }
          echo "Disk usage before resize:"
          df -h
          echo "Listing all .img files in repo:"
          find /home/syed/actions-runner/_work -name "*.img"
          echo "Contents of images/ dir:"
          ls -la images/
          IMAGE_FILE=$(find . -name "kali-*.img" | head -n 1)
          if [ -z "$IMAGE_FILE" ]; then
            echo "Error: No Kali image file found"
            echo "Last 20 lines of build.log:"
            tail -n 20 build.log
            exit 1
          fi
          echo "Found image: $IMAGE_FILE"
          # Resize image to 20 GB
          sudo truncate -s 20G "$IMAGE_FILE"
          sudo e2fsck -f -y "$IMAGE_FILE" || { echo "e2fsck failed even with -y"; sudo fdisk -l "$IMAGE_FILE"; exit 1; }
          sudo resize2fs -f -p "$IMAGE_FILE" || { sudo losetup -f "$IMAGE_FILE"; sudo resize2fs -f -p "$IMAGE_FILE"; }
          # Mount boot partition
          BOOT_OFFSET=$(sudo fdisk -l "$IMAGE_FILE" | grep -m1 'img1' | awk '{print $2 * 512}')
          if [ -z "$BOOT_OFFSET" ]; then
            echo "Error: Could not determine boot offset, falling back to 1048576"
            BOOT_OFFSET=1048576
          fi
          echo "Using boot offset: $BOOT_OFFSET"
          sudo mkdir -p /mnt/boot
          sudo mount -o loop,offset=$BOOT_OFFSET "$IMAGE_FILE" /mnt/boot || { echo "Boot mount failed"; sudo fdisk -l "$IMAGE_FILE"; exit 1; }
          sudo cp ../kernel-build/kernel8.img /mnt/boot/
          sudo cp ../kernel-build/*.dtb /mnt/boot/
          sudo cp -r ../kernel-build/overlays /mnt/boot/
          sudo umount /mnt/boot
          # Mount root partition
          ROOT_OFFSET=$(sudo fdisk -l "$IMAGE_FILE" | grep -m1 'img2' | awk '{print $2 * 512}')
          if [ -z "$ROOT_OFFSET" ]; then
            echo "Error: Could not determine root offset, falling back to 5242880"
            ROOT_OFFSET=5242880
          fi
          echo "Using root offset: $ROOT_OFFSET"
          sudo mkdir -p /mnt/root
          sudo mount -o loop,offset=$ROOT_OFFSET "$IMAGE_FILE" /mnt/root || { echo "Root mount failed"; sudo fdisk -l "$IMAGE_FILE"; exit 1; }
          sudo cp -r ../kernel-build/lib/modules/* /mnt/root/lib/modules/
          sudo cp -r ../kernel-source /mnt/root/usr/src/linux
          echo "Disk usage after resize:"
          df -h

      - name: Upload Error Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: kali-arm/build.log
          if-no-files-found: warn

      - name: Install Pentesting Tools and Drivers
        run: |
          cd kali-arm
          sudo systemd-nspawn -D /mnt/root /bin/bash -c "
            apt clean
            apt update
            apt install -y kali-linux-default aircrack-ng kismet bluez bluez-tools btscanner dkms
            git clone https://github.com/aircrack-ng/rtl8188eus.git
            cd rtl8188eus
            make -j$(nproc) KDIR=/usr/src/linux
            make install KDIR=/usr/src/linux
            modprobe 8188eu
          "

      - name: Install CSR Bluetooth Firmware
        run: |
          cd kali-arm
          sudo systemd-nspawn -D /mnt/root /bin/bash -c "
            apt clean
            apt update
            apt install -y firmware-linux firmware-linux-nonfree
            mkdir -p /lib/firmware
            wget -O /lib/firmware/BCM20702A0-0a12-0001.hcd \
              'https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm/BCM20702A0-0a12-0001.hcd'
          "

      - name: Cleanup Mounts and Compress Image
        run: |
          sudo umount /mnt/root
          cd kali-arm/images
          xz -T0 -v *.img

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: kali-arm/build.log
          if-no-files-found: warn

      - name: Upload Kali Linux Image
        uses: actions/upload-artifact@v4
        with:
          name: kali-linux-raspberrypi4-custom
          path: kali-arm/images/*.img.xz
          if-no-files-found: error
