name: Build Kali Linux for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y systemd-container debootstrap qemu-user-static \
          systemd-nspawn curl wget git mmdebstrap eatmydata ncurses-bin

      - name: Clone Kali ARM Build Scripts
        run: |
          git clone https://gitlab.com/kalilinux/build-scripts/kali-arm.git
          cd kali-arm

      - name: Run Raspberry Pi Build Script
        run: |
          cd kali-arm
          sudo bash -x ./raspberry-pi.sh 2>&1 | tee build.log
          exit ${PIPESTATUS[0]}

      - name: Debug: List Files in Images Directory
        run: ls -l kali-arm/images/

      - name: Upload Built Image
        uses: actions/upload-artifact@v4
        with:
          name: kali-linux-raspberrypi
          path: kali-arm/images/*.img.xz
          if-no-files-found: warn
