name: Build Kali Linux for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y systemd-container debootstrap qemu-user-static \
          curl wget git mmdebstrap eatmydata ncurses-bin || exit 1

      - name: Clone Kali ARM Build Scripts
        run: |
          git clone https://gitlab.com/kalilinux/build-scripts/kali-arm.git
          cd kali-arm
          chmod +x raspberry-pi.sh
          chmod +x common.d/build_deps.sh

      - name: Run Required Dependency Script
        run: |
          cd kali-arm
          sudo ./common.d/build_deps.sh || exit 1

      - name: Set Safe TERM Variable
        run: echo "TERM=xterm-256color" >> $GITHUB_ENV

      - name: Build Custom Kali Image (Show Full Errors)
        run: |
          cd kali-arm
          sudo bash -x ./raspberry-pi.sh 2>&1 | tee build.log
          exit ${PIPESTATUS[0]}

      - name: Debug - Show Full Build Log
        if: failure()
        run: |
          echo "Dumping full build log..."
          cat kali-arm/build.log || echo "No build log found!"

      - name: Debug - Find Image File Anywhere
        run: |
          echo "Searching for built image..."
          find kali-arm/ -type f -name "*.img.xz" > found_images.txt || echo "No image files found!"
          cat found_images.txt

      - name: Upload Build Logs (If Build Fails)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: kali-arm/build.log

      - name: Move Image to Known Location
        if: success()
        run: |
          IMAGE_PATH=$(cat found_images.txt | head -n 1)
          if [[ -f "$IMAGE_PATH" ]]; then
            echo "Found image at: $IMAGE_PATH"
            mv "$IMAGE_PATH" kali-linux-raspberrypi.img.xz
          else
            echo "No image file found!"
            exit 1
          fi

      - name: Upload Image as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kali-linux-raspberrypi
          path: kali-linux-raspberrypi.img.xz
